### ISSUE TITLE
JS Print Manager not working

### ISSUE THREAD

**Issue by tanveer12332** [rodriwasabi/JSPrintManager-Angular#10] opened 2020-11-26 09:52 UTC
js print manger install my pc v.3.0.20 but your demo application not find and showing alert message "download jsmanager" how i can fix it

**Comment by tanveer12332** [comment] 2020-11-26 09:53
![image](https://user-images.githubusercontent.com/6282477/100335799-335b9680-2ff7-11eb-9cf8-16355a2db284.png)

**Comment by Karthickdev** [comment] 2020-12-29 13:02
Facing the same problem.. @tanveer12332 did you find any solutions?

**Comment by tanveer12332** [comment] 2020-12-31 10:14
no any solutions. still error

**Comment by rodriwasabi** [comment] 2021-01-01 20:28
Hey guys, I've taken a look and it looks like that now version 3 has changed some features like the port for JSPrinterManager client. For v2 was 22443, now v3 uses 23443. 
So for simplicity it is recommended to **use version 2 of JSPrinterManager**. Otherwise there should be a port of v3 using files from 
https://github.com/neodynamic/JSPrintManager/tree/master/scripts 
and changing them on ./src/assets/js/ on this repo.
Hope this helps

**Comment by rodriwasabi** [comment] 2021-01-01 20:43
Confirmed. Please install version 2:
https://www.neodynamic.com/downloads/jspm/jspm2.aspx

![image](https://user-images.githubusercontent.com/7326791/103445952-7fca6f80-4c50-11eb-864f-3381e236ba1b.png)
Closing this one.

**Closed as completed by rodriwasabi** 2021-01-01 20:43 UTC

**Comment by tanveer12332** [comment] 2021-01-02 13:14
ok let me check then i will update you
